Add setting option to hide item count limit on menu entries
jellyfin/jellycon pull request #320
Opened 2024-02-28 12:00 UTC by hagaygo

As a new user the number count at the end of "Next Up (20)" kept me thinking the list contains 20 items while it is a const regardless of the content (which can be nice idea to implement).

So i added a setting option that allow the user to hide , so users who wants to keep it, can have the old behavior (I personally think it should be hidden as default)

While implementing the settings the logic of adding the item count at the end of the menu item was scattered at many places (with some place using simple concatenation and other places using format) i added a function under utils that handles the settings and visual logic at just one place.

New setting (default is "off"):

![image](https://github.com/jellyfin/jellycon/assets/5015856/81769777-3a18-4243-b049-eb83ed90238b)

Default view :

![image](https://github.com/jellyfin/jellycon/assets/5015856/782d0a80-f369-40d5-86ba-18993f59d05f)

With new setting turned "on" : 

![image](https://github.com/jellyfin/jellycon/assets/5015856/c2f9ab49-09d0-4079-87c4-71dc3f0e4678)

2024-03-23 18:49 UTC, mcarlton00 commented
> As a new user the number count at the end of "Next Up (20)" kept me thinking the list contains 20 items while it is a const regardless of the content (which can be nice idea to implement).

I'm not quite sure what you mean by this.  It has a limit of 20 items displayed, which is configurable from the `settings -> Interface -> Number of items to show in filtered lists`.  And to me it seems better to have that be displayed by default than to have no indication that it's a limited length list and have users confused about why they're "missing" content.

2024-03-23 19:11 UTC, hagaygo commented
I assumed you (as the maintainer) prefers the current view which is still the default with my PR.

As i mentioned from my experience this is confusing and redundant to keep seeing this number over and over again.

So i think having the option to hide it provides only pros and benefits since it causes no harm.

Do note , the PR contains also code improvement since it removes duplicates and puts the format code and logic in one place.

2024-03-28 21:06 UTC, mcarlton00 commented
Right, I understand the change and the code cleanup, I just couldn't understand what you were actually expecting from that, it sounded like something different.  I got it now

2024-03-28 21:14 UTC, mcarlton00 requested changes

2024-03-28 21:14 UTC, mcarlton00 commented on resources/settings.xml
> +		<setting id="hide_unwatched_details" type="bool" label="30023" default="false" visible="true" enable="true" />
```suggestion
		<setting id="hide_unwatched_details" type="bool" label="30023" default="false" visible="true" enable="true" />
```

big whitespace block again

2024-03-28 21:14 UTC, mcarlton00 commented on resources/lib/menu_functions.py
> +    add_menu_directory_item(('{}{} ' + get_filtered_items_count_text()).format(view_name, translate_string(30349)), url)
I personally don't like this formatting.  Mixing string concatenation methods like this seems arbitrarily confusing compared to leaving the placeholders and doing it as an argument like the other variables here.
```suggestion
    add_menu_directory_item('{}{}{}'.format(view_name, translate_string(30349), get_filtered_items_count_text()), url)
```
Also, the `get_filtered_items_count_text()` already includes a space at the front of the string, so including it here as well results in a double space

2024-03-28 21:14 UTC, mcarlton00 commented on resources/lib/menu_functions.py
> +    add_menu_directory_item(('{}{}' + get_filtered_items_count_text()).format(view_name, translate_string(30267)), url)
again

2024-03-28 21:14 UTC, mcarlton00 commented on resources/lib/menu_functions.py
> +    add_menu_directory_item(('{}{} ' + get_filtered_items_count_text()).format(view_name, translate_string(30268)), url)
again

2024-03-28 22:10 UTC, hagaygo commented
Your comments should be fixed now.

Just saw your comment on other PR to not perform force push , sorry but i not sure how to update the code and keep it to a one commit without force pushing.

On the last compare it should be easy to see the changes.

2024-04-02 23:40 UTC, mcarlton00 approved these changes
There's no reason to force things to only be 1 commit per PR.  You can have multiple commits in a single PR, and it's generally preferable so that everything is easier to be tracked as long as they're descriptive PR titles.  Force pushes erases review history, so especially if you're trying to submit something larger it creates more work on the reviewer to find the differences between initial review and current review and make sure the right things were changed.

2024-04-02 23:40 UTC, merged